# Generated by Django 5.1.2 on 2024-10-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit_comparison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='focal_length',
            field=models.IntegerField(default=28),
            preserve_default=False,
        ),
    ]
