# Generated by Django 5.1.2 on 2024-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kit_comparison", "0002_lens_focal_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lens",
            options={"verbose_name_plural": "Lenses"},
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lenses", models.ManyToManyField(to="kit_comparison.lens")),
            ],
        ),
    ]
