# Generated by Django 5.1.2 on 2024-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kit_comparison", "0003_alter_lens_options_kit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lens",
            name="focal_length",
            field=models.CharField(max_length=10),
        ),
    ]
